//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCRAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SATIS
    {
        public int ID { get; set; }
        public Nullable<int> URUN_ID { get; set; }
        public Nullable<int> PERSONEL_ID { get; set; }
        public Nullable<int> MUSTERI_ID { get; set; }
        public Nullable<decimal> FIYAT { get; set; }
        public Nullable<int> ADET { get; set; }
    
        public virtual MUSTERI MUSTERI { get; set; }
        public virtual PERSONEL PERSONEL { get; set; }
        public virtual URUN URUN { get; set; }
    }
}
