//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCRAPP.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public URUN()
        {
            this.SATIS = new HashSet<SATIS>();
        }
    
        public int ID { get; set; }
        public string URUN_AD { get; set; }
        public string URUN_MARKA { get; set; }
        public Nullable<int> KATEGORI_ID { get; set; }
        public Nullable<decimal> GELIS_FIYAT { get; set; }
        public Nullable<decimal> ETIKET_FIYAT { get; set; }
        public Nullable<int> STOK { get; set; }
        public Nullable<bool> DURUM { get; set; }
    
        public virtual KATEGORI KATEGORI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SATIS> SATIS { get; set; }
    }
}
